# permissions for end users to view customredis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customredis-viewer-role
rules:
- apiGroups:
  - redis.hongqchen
  resources:
  - customredis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.hongqchen
  resources:
  - customredis/status
  verbs:
  - get
